version: '2'
services:
    swoft:
        image: swoft/swoft:latest
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www/swoft
        stdin_open: true
        tty: true
        command: php /var/www/swoft/bin/swoft start
